sudo: required
services: "-docker"
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: "gdUEyJQ0v7l9PE14aIffBitstSFOagNYHHSfYFlF/095WEEQmtBG3gBfJf3Ca00JxPpAIASz4GyQlVcT0n+Q4qOIWdgclAJ6dVwNxtWCu0/6hrLk3E78RuiwBh0t1KGq7zC+IYgjdXpsVX3M8fC/WnIsEAFbBCNhLoLCQgoVGxoH9f5tIQogKrmNCCgXNxhxgmtuFVxjJK8iN4uUTeu2K0FeNf/ekWpSrAHjzm125283AeARyD2A8WtK40Cuuk/5T2it6rlUuEpQcume5HCz9yXnxZtbVOoH6tPWjYM++sOO9jqZZmwaEK2vIYX1KC792p+kvZRdYJ+Zz3hFjKy1LakApRH9ubPd0spXyVq9nj9QP7N9YFiNW1aJe+V6Cw4NTYBT0qeZvJ7QWlgYqFr7iPWsypO8uzU2aZ36gk3NNzO/XMJSbAAJDJR2EfV4PtoIq5PHfTT0ao1gzbekZCy/ro2TEFW90AYOWfBxcQZeRcKjg/LAGuWZ/1/T1zEhZ4jlwGFo9v0I3k/9tqTxGshiwZpZXTZ1j0jY0Ynx8Uz/uFsbGRVDdKXXWkjrkfuOKYdT+vZAdmHCWo79HF48NrNnFvmGMP3NBKHIszbr8s4PJluzAY8ibs/fMXl8FLliH/0GWDtHgK/HWsqYZajkv+7/GBKspStHaZxYivTkkt8QOLE="
  on: heroku_production
  app: probot-slinshady89
