sudo: required
services: "-docker"
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: U2wWWxyxkY2GV7hg76/gfppKJZT18JzFFeK/2I86u+fXW05KdVgkrqUG4iPuREOJ0IrtipHjeNo7QPWkBB1qzeAzVNVjhUwvJbA42y/tyHDEuGc2ZCePKySHPhLlyBblVC4+GSJS6E0wO4+L2GKF+McfmDcRzCtib1NWeDr0osJNlzxuAW4l8/NkT/SASLR3AYMpCUm7RNR1cIb9Ugu91Qn5chkovWY6nA32w5qqsv3QoLUrNUXWTnMJFgmPz87BzV+sS5EWQ0RupmMGSaQwScDj0xJxGjkdVxmqOHcBZbo0VMWR0Qde4+dwR3y20w0zQjEZnb9qoBAM2SsF59aDzk4+s1W9twKclA8MQDdS5Q+Uaqs9haD8hbtmZlNoQeI5ygSM6d6ZiV9FYbNOAnV6xljf2L+n11inhJ2EWilMydO00POQvBUp+nkTX3eUeMnBAf4F+3dpG76w4OeovftL5ANP1vp1KRj7HVNBBW4sjDicne/MLW484tHZjEy28qa/kAmQyGoxBmMIpFQjV/M+K0X9alegA3WnVKhjI3mWkaDPshaP0yI+REDZZ1qI75KIVNSpc0g2k/1jn5h8YB3NX1+PrgLOAiKb0u7QMz/t1EUadU7o3mqtNKFwRSNiXfUx9dbbhQJ42r4uNCQ+q8mrJfooZFklr+BInSR2fjF2ctU=
  on: heroku_production
  app: probot-slinshady89
